env:
  global:
  - secure: M+782Uk76eaQIKY5BQKt8DUVSyGaIQKzsPCw115CeucCanT09S0J9bMStVNEevPg1LKcdi8iTr0IgIFB9b3mZsD1T/HzAfsGNmnl94GzTIPAHU2mrMd2C8sHhs0yX5MYL31GxGKPRpZ07zkOgEgU4f/hCInz1fTTA/5NOxLBxaY=
  - secure: Pbm2omnJmT4YFlbYsamirZCe6d38sXAa12ZvRoTms4xry7neuniHTorx4w1h4mRFMMkzzWJYB8H6deQ0yZ1Ln6OVJWT8TnR4guWY0mFzacMSmvO6KcDI+CXCO1X8H3HtYrHFL3lz7iQe424fgcDrEcoejP0TFdDjJ7CEDbsiVDA=

sudo: false

rvm:
  - "2.4"
node_js:
  - "4"

branches:
  only:
    - master

before_install: npm install -g grunt-cli

install:
  - npm install
  - bundle install --deployment --jobs=3 --retry=3

cache:
  directories:
    - vendor/bundle
    - node_modules

script: grunt build

after_success:
  - bundle exec s3_website push
